theme = "catppuccin-frappe"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
color-modes = true
completion-replace = true
auto-completion = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false
display-messages = false

[editor.file-picker]
ignore = true
hidden = true
git-ignore = true

[keys.normal]
G = "goto_last_line"
D = "kill_to_line_end"
tab = "repeat_last_motion"
S-s = "goto_line_start"
S-e = "goto_line_end"
